openapi: 3.0.3
info:
  title: XQ Fitness Write Service API
  description: Write service for creating, updating, and deleting workout routines and related data
  version: 1.1.0
  contact:
    name: XQ Fitness Team

servers:
  - url: http://localhost:3000/api/v1
    description: Local development server

paths:
  /routines:
    post:
      summary: Create a new workout routine
      description: Creates a new workout routine
      operationId: createRoutine
      tags:
        - Routines
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRoutineRequest'
      responses:
        '201':
          description: Routine created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoutineResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /routines/{routineId}:
    put:
      summary: Update a workout routine
      description: Updates an existing workout routine
      operationId: updateRoutine
      tags:
        - Routines
      parameters:
        - name: routineId
          in: path
          description: ID of the routine to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRoutineRequest'
      responses:
        '200':
          description: Routine updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoutineResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Routine not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete a workout routine
      description: Deletes a workout routine and all associated data
      operationId: deleteRoutine
      tags:
        - Routines
      parameters:
        - name: routineId
          in: path
          description: ID of the routine to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Routine deleted successfully
        '404':
          description: Routine not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /workout-days:
    post:
      summary: Create a new workout day
      description: Creates a new workout day for a routine
      operationId: createWorkoutDay
      tags:
        - Workout Days
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWorkoutDayRequest'
      responses:
        '201':
          description: Workout day created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkoutDayResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Routine not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /workout-days/{dayId}:
    put:
      summary: Update a workout day
      description: Updates an existing workout day
      operationId: updateWorkoutDay
      tags:
        - Workout Days
      parameters:
        - name: dayId
          in: path
          description: ID of the workout day to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWorkoutDayRequest'
      responses:
        '200':
          description: Workout day updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkoutDayResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Workout day not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete a workout day
      description: Deletes a workout day and all associated sets
      operationId: deleteWorkoutDay
      tags:
        - Workout Days
      parameters:
        - name: dayId
          in: path
          description: ID of the workout day to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Workout day deleted successfully
        '404':
          description: Workout day not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /workout-day-sets:
    post:
      summary: Add sets configuration to a workout day
      description: Creates a new sets configuration for a muscle group on a workout day
      operationId: createWorkoutDaySet
      tags:
        - Workout Day Sets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWorkoutDaySetRequest'
      responses:
        '201':
          description: Sets configuration created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkoutDaySetResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Workout day or muscle group not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /workout-day-sets/{setId}:
    put:
      summary: Update sets configuration
      description: |
        Updates the number of sets for a muscle group on a workout day.
        
        **Usage options:**
        1. Provide `setId` in the path (e.g., `/workout-day-sets/123`) - traditional method
        2. Provide `workoutDayId` and `muscleGroupId` as query parameters (e.g., `/workout-day-sets/0?workoutDayId=1&muscleGroupId=2`) - alternative method when setId is unknown
        
        When query parameters are provided, they take precedence and the setId in the path is ignored.
      operationId: updateWorkoutDaySet
      tags:
        - Workout Day Sets
      parameters:
        - name: setId
          in: path
          description: ID of the sets configuration to update. Can be any value (e.g., 0) when using query parameters.
          required: true
          schema:
            type: integer
            format: int64
        - name: workoutDayId
          in: query
          description: ID of the workout day (alternative to setId). Must be provided together with muscleGroupId.
          required: false
          schema:
            type: integer
            format: int64
        - name: muscleGroupId
          in: query
          description: ID of the muscle group (alternative to setId). Must be provided together with workoutDayId.
          required: false
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWorkoutDaySetRequest'
      responses:
        '200':
          description: Sets configuration updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkoutDaySetResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Sets configuration not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete sets configuration
      description: Removes a sets configuration from a workout day
      operationId: deleteWorkoutDaySet
      tags:
        - Workout Day Sets
      parameters:
        - name: setId
          in: path
          description: ID of the sets configuration to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Sets configuration deleted successfully
        '404':
          description: Sets configuration not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    CreateRoutineRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
          example: "Push Pull Legs"
        description:
          type: string
          maxLength: 1000
          example: "3-day split focusing on push, pull, and leg movements"
        isActive:
          type: boolean
          default: true

    UpdateRoutineRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
          example: "Updated Routine Name"
        description:
          type: string
          maxLength: 1000
          example: "Updated description"
        isActive:
          type: boolean

    RoutineResponse:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Push Pull Legs"
        description:
          type: string
          example: "3-day split focusing on push, pull, and leg movements"
        isActive:
          type: boolean
          example: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CreateWorkoutDayRequest:
      type: object
      required:
        - routineId
        - dayNumber
        - dayName
      properties:
        routineId:
          type: integer
          format: int64
          example: 1
        dayNumber:
          type: integer
          minimum: 1
          example: 1
        dayName:
          type: string
          minLength: 1
          maxLength: 100
          example: "Push Day"
        notes:
          type: string
          maxLength: 1000
          example: "Focus on chest and shoulders"

    UpdateWorkoutDayRequest:
      type: object
      properties:
        dayNumber:
          type: integer
          minimum: 1
          example: 1
        dayName:
          type: string
          minLength: 1
          maxLength: 100
          example: "Updated Push Day"
        notes:
          type: string
          maxLength: 1000
          example: "Updated notes"

    WorkoutDayResponse:
      type: object
      required:
        - id
        - routineId
        - dayNumber
        - dayName
      properties:
        id:
          type: integer
          format: int64
          example: 1
        routineId:
          type: integer
          format: int64
          example: 1
        dayNumber:
          type: integer
          example: 1
        dayName:
          type: string
          example: "Push Day"
        notes:
          type: string
          example: "Focus on chest and shoulders"
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CreateWorkoutDaySetRequest:
      type: object
      required:
        - workoutDayId
        - muscleGroupId
        - numberOfSets
      properties:
        workoutDayId:
          type: integer
          format: int64
          example: 1
        muscleGroupId:
          type: integer
          format: int64
          example: 1
        numberOfSets:
          type: integer
          minimum: 1
          example: 4
        notes:
          type: string
          maxLength: 1000
          example: "Focus on progressive overload"

    UpdateWorkoutDaySetRequest:
      type: object
      properties:
        numberOfSets:
          type: integer
          minimum: 1
          example: 5
        notes:
          type: string
          maxLength: 1000
          example: "Updated notes"

    WorkoutDaySetResponse:
      type: object
      required:
        - id
        - workoutDayId
        - muscleGroupId
        - numberOfSets
      properties:
        id:
          type: integer
          format: int64
          example: 1
        workoutDayId:
          type: integer
          format: int64
          example: 1
        muscleGroupId:
          type: integer
          format: int64
          example: 1
        numberOfSets:
          type: integer
          example: 4
        notes:
          type: string
          example: "Focus on progressive overload"
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: "VALIDATION_ERROR"
        message:
          type: string
          example: "Invalid request parameters"
        timestamp:
          type: string
          format: date-time
        details:
          type: array
          items:
            type: string
